SHOW USER;

DROP TABLE ORDERS CASCADE CONSTRAINTS PURGE;



DROP TABLE PRODUCT CASCADE CONSTRAINTS PURGE;



DROP TABLE MEMBER CASCADE CONSTRAINTS PURGE;



DROP TABLE TB_ZIPCODE CASCADE CONSTRAINTS PURGE;



CREATE TABLE MEMBER
(
	ID                   DATE DEFAULT  SYSDATE  NOT NULL ,
	PWD                  VARCHAR2(30) NULL ,
	NAME                 VARCHAR2(20) NULL ,
	ADDRESS              VARCHAR2(20) NULL ,
	TEL                  VARCHAR2(30) NULL ,
	INDATE               DATE DEFAULT  SYSDATE  NULL ,
	ZIPCODE              VARCHAR2(30) NOT NULL 
);



CREATE UNIQUE INDEX XPK회원 ON MEMBER
(ID   ASC);



ALTER TABLE MEMBER
	ADD CONSTRAINT  XPK회원 PRIMARY KEY (ID);



CREATE TABLE ORDERS
(
	ID                   DATE DEFAULT  SYSDATE  NOT NULL ,
	PRODUCT_CODE         VARCHAR2(30) NOT NULL ,
	O_SEQ                VARCHAR(20) NOT NULL ,
	PRODUCT_SIZE         VARCHAR2(5) NULL ,
	QUANTITY             VARCHAR2(10) NULL ,
	RESULT               CHAR(1) NULL ,
	INDATE               DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX XPK주문 ON ORDERS
(O_SEQ   ASC);



ALTER TABLE ORDERS
	ADD CONSTRAINT  XPK주문 PRIMARY KEY (O_SEQ);



CREATE TABLE PRODUCT
(
	PRODUCT_CODE         VARCHAR2(20) NOT NULL ,
	PRODUCT_NAME         VARCHAR2(30) NULL ,
	PRODUCT_KIND         VARCHAR2(30) NULL ,
	PRODUCT_PRICE1       VARCHAR2(10) NULL ,
	PRODUCT_PRICE2       VARCHAR2(10) NULL ,
	PRODUCT_CONTENTS     VARCHAR2(20) NULL ,
	PRODUCT_IMAGE        VARCHAR2(10) NULL ,
	SIZE_ST              VARCHAR2(5) NULL ,
	SIZE_ED              VARCHAR2(5) NULL ,
	PRODUCT_QUANTITY     VARCHAR2(30) NULL ,
	USEYN                VARCHAR2(5) NULL ,
	INDATE               DATE DEFAULT  SYSDATE  NULL 
);



CREATE UNIQUE INDEX XPK상품 ON PRODUCT
(PRODUCT_CODE   ASC);



ALTER TABLE PRODUCT
	ADD CONSTRAINT  XPK상품 PRIMARY KEY (PRODUCT_CODE);



CREATE TABLE TB_ZIPCODE
(
	ZIPCODE              VARCHAR2(30) NOT NULL ,
	SIDO                 VARCHAR2(30) NULL ,
	GUGUN                VARCHAR2(30) NULL ,
	DONG                 VARCHAR2(30) NULL ,
	BUNGI                VARCHAR2(30) NULL 
);



CREATE UNIQUE INDEX XPK우편번호 ON TB_ZIPCODE
(ZIPCODE   ASC);



ALTER TABLE TB_ZIPCODE
	ADD CONSTRAINT  XPK우편번호 PRIMARY KEY (ZIPCODE);



ALTER TABLE MEMBER
	ADD (CONSTRAINT R_2 FOREIGN KEY (ZIPCODE) REFERENCES TB_ZIPCODE (ZIPCODE));



ALTER TABLE ORDERS
	ADD (CONSTRAINT R_3 FOREIGN KEY (ID) REFERENCES MEMBER (ID));



ALTER TABLE ORDERS
	ADD (CONSTRAINT R_5 FOREIGN KEY (PRODUCT_CODE) REFERENCES PRODUCT (PRODUCT_CODE));



















