SHOW USER;

CREATE TABLE RELATED_PARCEL_NUMBER(
    ROAD_NUM VARCHAR2(26),
    BUB_CODE VARCHAR2(10),
    SIDO_NAME VARCHAR2(40),
    SIGUNGU VARCHAR2(40),
    MYUNDONG VARCHAR2(40),
    JEONGLI VARCHAR2(40),
    MOUNTAIN VARCHAR2(1),
    BUNJI NUMBER(4),
    HO  NUMBER(4),
    ROADCODE VARCHAR2(12),
    UNDERGROUND VARCHAR2(1),
    BUILDMN NUMBER(5),
    BUILDSN NUMBER(5),
    MOVECODE VARCHAR2(2)
    
);

COMMIT;

DROP TABLE RELATED_PARCEL_NUMBER;





